pipeline {
    agent  {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "122610517295"
        PROJECT = "roboshop"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    /* parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password') 
    } */
    // Build
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Bastion EKS ACM ALB') {
            parallel {  // this block allows us to define multiple stages that will be executed in parallel, in this case we have three stages: Trigger Bastion, Trigger EKS, and ACM. Each of these stages will be executed simultaneously, which can help reduce the overall execution time of the pipeline when there are independent tasks that can be run at the same time. This is particularly useful in scenarios where we have multiple components or services that need to be deployed or configured, and they do not have dependencies on each other.
                stage('Trigger Bastion') {
                    steps {
                        script {
                            build job: '20-bastion', 
                            propagate: false,  // even SG fails VPC will not be effected
                            wait: false // VPC will not wait for SG pipeline completion
                        }
                    }
                }
                stage('Trigger EKS') {
                    steps {
                        script {
                            build job: '80-eks', 
                            propagate: false,  // even SG fails VPC will not be effected
                            wait: false // VPC will not wait for SG pipeline completion
                        }
                    }
                }
                stage('ACM') {
                    steps {
                        script {
                            build job: '60-acm', 
                            propagate: false,  // even SG fails VPC will not be effected
                            wait: false // VPC will not wait for SG pipeline completion
                        }
                    }  
                }
            }
        }
        stage('Trigger ALB') {
            steps {
                script {
                    build job: '70-frontend-alb', 
                    propagate: false,  // even SG fails VPC will not be effected
                    wait: false // VPC will not wait for SG pipeline completion
                }
            }
        }

        
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}