pipeline {
    agent  {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "122610517295"
        PROJECT = "roboshop"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    /* parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password') 
    } */
    // Build
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 20-bastion
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 20-bastion
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 20-bastion
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        
    }

    post { 
        always { 
            echo 'I will always say Hello again!' // this block will always execute regardless of the build result, it is used to perform cleanup actions or any necessary steps that should be executed after every build, in this case we are deleting the workspace directory to clean up any files or artifacts generated during the build process and also printing a message to indicate that this block has been executed.
            deleteDir()
        }
        success { 
            echo 'Hello Success' // this block will execute only if the build is successful, it is used to perform actions that should only be executed when the build succeeds, in this case we are printing a message to indicate that the build was successful.  
        failure { 
            echo 'Hello Failure'
        }
    }
}